---
title: "Titanic Data Analysis"
author: "Susrutha Gongalla"
date: "October 8, 2015"
output: html_document
---

This document performs data analysis of titanic dataset available on kaggle
```{r, echo=FALSE, message=FALSE, warning=FALSE}
setwd("C:/Users/Susrutha/Desktop/Kaggle/Titanic")
library(party)
library(plyr)
library(ggplot2)

```

Starting the analysis by first loading the data
```{r}
# Loading the training and test data
trainData <- read.csv("C:/Users/Susrutha/Desktop/Kaggle/Titanic/train.csv", header = T)
testDataComplete <- read.csv("C:/Users/Susrutha/Desktop/Kaggle/Titanic/test.csv", header = T)

# Transforming attribute domains to their appropriate classes
trainData <- transform(trainData, Survived = as.factor(Survived),   
                       Pclass = as.factor(Pclass),
                       Name = as.character(Name))

trainData <- trainData[complete.cases(trainData),]  # Getting rid of rows with missing values

```

Building a decision tree to be able to predict survival
```{r, fig.width=12, fig.height=6}

# Build a decision tree using the variables that may actually affect the survival outcome
decisionTreeModel <- ctree(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare 
                           + Embarked, data = trainData)
plot(decisionTreeModel, type = "simple")
```

Use the decision tree to make prediction
```{r}
testData <- testDataComplete[,c(2, 4, 5, 6, 7, 9, 11)]
testData <- transform(testData, Pclass = as.factor(Pclass))
levels(testData$Embarked) <- levels(trainData$Embarked)
pred <- predict(decisionTreeModel, testData)
results <- data.frame(PassengerId = testDataComplete[,1], Survived = pred)
```

Use Random forests for predicting survival
```{r}
set.seed(10)
rfModel <- cforest(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare 
                           + Embarked, data = trainData)
rfPred <- predict(rfModel, testData, OOB = TRUE)
rfResults <- data.frame(PassengerID = testDataComplete[,1], Survived = rfPred)
```


